### ISSUE TITLE
Update for the Ref Genome GRCm39

### ISSUE THREAD

**Issue by luckysardar** [FelixKrueger/reStrainingOrder#4]
As SNPsplit update can you please provide the update for reStrainingOrder

Thank you

**Comment by FelixKrueger** [comment]
I had actually started on this already, and will continue with it as soon as my current load allows. Thanks for requesting.

**Comment by FelixKrueger** [comment]
I have now updated `reStrainingOrder` to use the v8 annotation file, and the `GRCm39` mouse genome build from Ensembl. 

A new release (v0.4.0) is available here: https://github.com/FelixKrueger/reStrainingOrder/releases/tag/0.4.0
